DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS orders CASCADE;


CREATE TABLE IF NOT EXISTS vehicles (
    id SERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    license_plate VARCHAR(50) NOT NULL,
    capacity INT NOT NULL ,
    speed INT NULL
);



CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    destination VARCHAR(255) NOT NULL,
    shippingType VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    cost DOUBLE PRECISION NOT NULL
);
