DROP TABLE IF EXISTS shipping_requests;

CREATE TABLE shipping_requests (
   id SERIAL PRIMARY KEY,   vehicle_type VARCHAR(50) NOT NULL,
   payload_weight DOUBLE PRECISION NOT NULL,
   velocity DOUBLE PRECISION NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS vehicles;

CREATE TABLE  vehicles (
    id SERIAL PRIMARY KEY,    vehicle_type VARCHAR(50) NOT NULL,
    payload_weight DOUBLE PRECISION NOT NULL,
    velocity DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);